In [1]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor

In [4]:
import os
import  pickle
import h5py
import json

class CustomImageDataset(Dataset):
    def __init__(self, mode = "train"):
        if mode == "train":
            with open("./train.txt", "r") as f:
                self.datalist = f.readlines()
        elif mode == "test":
            with open("./test.txt", "r") as f:
                self.datalist = f.readlines()
        text_tmp = open("data.json")
        data = json.load(text_tmp)
        ann = {"假": 0, "真": 1, "辟谣": 2}
        self.label_dict = {}
        for i in data:
            self.label_dict[i["video_id"]] = ann[i["annotation"]]

    def __len__(self):
        return len(self.datalist)

    def __getitem__(self, idx):
        imf = open('/mnt/c/Users/IT/Downloads/all/ptvgg19_frames/'+self.datalist[idx].strip()+'.pkl', 'rb')
        data_imf = pickle.load(imf)
        vf = h5py.File('/mnt/c/Users/IT/Downloads/all/c3d/'+self.datalist[idx].strip()+'.hdf5', 'r')
        data_vf = vf[self.datalist[idx].strip()]["c3d_features"][:]
        af = open('/mnt/c/Users/IT/Downloads/all/audiosconvfea/'+self.datalist[idx].strip(), 'rb')
        data_af = pickle.load(af)
        label = self.label_dict[self.datalist[idx].strip()]

        return data_imf, data_vf, data_af, label

In [5]:
c = CustomImageDataset()

In [6]:
data_imf, data_vf, data_af, label = c[10]

In [7]:
data_imf.shape, data_vf.shape, data_af.shape

((28, 4096), (28, 4096), (20, 12288))

In [60]:
data_imf

array([[-0.02978136,  0.5214211 , -2.2010493 , ..., -0.25699484,
        -0.8722791 , -1.8240757 ],
       [ 0.31891212,  0.20015962, -2.284183  , ..., -0.47997105,
        -0.7861618 , -2.415896  ],
       [ 0.67959756,  0.6448401 , -2.2429893 , ..., -0.54838455,
        -0.8340438 , -1.8753573 ],
       ...,
       [-0.66805995,  0.32872668, -0.6851071 , ..., -0.2504583 ,
        -0.45006207,  0.2953867 ],
       [-0.6856191 ,  0.3228754 , -0.6766888 , ..., -0.24488266,
        -0.43595433,  0.3240003 ],
       [-0.70799834,  0.31297606, -0.69428504, ..., -0.23087285,
        -0.4357256 ,  0.33114514]], dtype=float32)

In [61]:
data_vf

array([[0.21621627, 1.2825677 , 1.447454  , ..., 0.        , 1.7883198 ,
        0.12972558],
       [0.        , 1.1042053 , 0.47129965, ..., 0.        , 0.        ,
        0.7814119 ],
       [0.        , 0.00869048, 0.        , ..., 0.        , 0.        ,
        1.7861747 ],
       ...,
       [0.        , 0.        , 2.665276  , ..., 0.55926245, 0.        ,
        0.        ],
       [0.        , 0.        , 2.6870937 , ..., 0.95208526, 0.        ,
        0.        ],
       [0.        , 0.        , 2.6269674 , ..., 1.0240164 , 0.        ,
        0.        ]], dtype=float32)

text

In [36]:
import json

keywords = []
comments = []
count = 0

with open('./data_complete.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

for i in range(len(data)):
    keywords.append(data[i]["keywords"])
    comments.append(data[i]["comments"])
    if not data[i]["comments"]:
        count = count + 1
count

1647

In [34]:
len(comments)

3848

In [14]:
import json

keywords = []
comments = []
count = 0

with open('./data_complete.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

for i in range(len(data)):
    keywords.append(data[i]["keywords"])
    if data[i]["comments"]:
        comments.append(data[i]["comments"])
    break
#     if not data[i]["comments"]:
#         count = count + 1
# count

In [15]:
comments

[['吵吵什么，打台球没球了，让我拿过来当台球用了，一惊一乍的。',
  '或许我们都是某个巨大生物体内的寄生虫罢了、',
  '没事，不影响我过年就行',
  '恒星回家过年去了[捂脸]',
  '听物理老师说 我们人类是3维空间 肯定有4维的更高级的',
  '别的星球猪肉贵吗？',
  '其实人类已经在一个误区里了，谁说没有液态水没有氧气的地方不会存在生命？只是人类自己的定义罢了',
  '起初，没有人在意这场灾难。这只不过是一场山火，一次旱灾，一个物种的灭绝，一座城市的消失，直到这场灾难和每个人息息相关     ——《流浪地球》',
  '完了，是路法开着他的阿法斯号，来夺取地球能晶了[捂脸]',
  '都快过年了，能让我们安心过个好年吗？[笑哭]',
  '请问这一事件影响我回家过年不？[捂脸]',
  '被高级文明拿进小宇宙中开采物质了。',
  '这空间的时间，和那个空间的时间不一样，也许地球的时间比别的空间的时间慢呢，质量越大时间越快，质量越小，时间越快，或者不一样的空间时间也不一样',
  '是不是运动到了某个人类观测不到的区域',
  '我觉得，太阳，地球，月亮，银河系，黑洞，宇宙，都有自己的意识',
  '我觉得我看了这些，我开始怀疑人生了[捂脸][捂脸]',
  '得了吧，那颗星球各种元素都有，被我收进我的星辰子宇宙做备用实验星球了',
  '[爱心]',
  '这种现象并不罕见，恒星的命运就是这样啊！要么就是变成白矮星，冷却变成黑矮星，要么就是变成黑洞，变成超新星遗迹',
  '人类是否造出了比回地球更快的飞行器',
  '说不定在这10年的时间，那些恒星都已经存活了几百万年，只不过是爆炸时间有点差距而已。',
  '长知识了，[赞][赞][赞]',
  '晚上的星星好漂亮',
  '科学家应该研究研究自己 自己为什么是人类呢？',
  '北极星又是哪一颗恒星啊？[捂脸]',
  '应该是被星兽吞食了',
  '我今年夏天就看见一颗很亮的星星突然消失了，刚抬头看见它觉得好亮，然后一下子就消失了，我还以为自己看错了',
  '啥是常理',
  '科学家发现是至少100颗，我发现至少99颗，我也不差啊',
  '地球都没研究明白还研究宇宙',
  '我们看到的星星未必是恒星',
  '星星回家了',
  '人终究是人，怎么可能探索出宇宙的奥秘，

In [16]:
len(comments)

1

In [18]:
import torch
from transformers import BertTokenizer, BertModel

model_name = './bert-base-chinese/'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name)

indexed_keywords = [(i, keywords) for i, group in enumerate(keywords) for comment in group]

# 提取keywords特征
features = []
for i, comment in indexed_keywords:
    inputs = tokenizer(comment, return_tensors='pt', padding=True, truncation=True, max_length=50)
    outputs = model(**inputs)
    last_hidden_states = outputs.last_hidden_state

    feature = last_hidden_states.mean(dim=1)  
    features.append({
        'index': data[i]["video_id"],
        'input_ids': feature.flatten().detach().numpy()
    })

# 保存特征
features_path = './text_keywords.pt'
torch.save(features, features_path)

In [19]:
b = torch.load('./text_keywords.pt')

In [20]:
b

[{'index': '3x4zj7hyemptkvm',
  'input_ids': array([ 3.31136286e-01, -5.27080297e-02, -8.61083642e-02, -3.28927953e-03,
          5.10410130e-01,  1.73011228e-01, -2.29835033e-01,  2.82268465e-01,
         -3.37671816e-01,  3.77170026e-01,  1.28737852e-01, -3.13593328e-01,
          8.80487189e-02,  6.25338733e-01,  8.47829640e-01, -8.83926302e-02,
         -4.35855798e-02,  3.46386105e-01, -2.16170311e-01,  2.12434128e-01,
         -2.24721834e-01,  3.89261055e-03,  5.90885244e-02,  1.70138001e-01,
          5.85317433e-01, -4.66737658e-01,  5.74524462e-01, -4.26458955e-01,
          2.52191633e-01, -1.78976178e-01, -2.58813620e-01,  3.59810203e-01,
          5.98238781e-02,  3.09427008e-02, -8.68773833e-02, -1.42996653e-03,
         -8.05156350e-01,  1.03550829e-01, -5.02201676e-01, -4.95455831e-01,
          5.07095754e-01, -3.08932811e-01, -1.82036042e-01, -3.53716850e-01,
          1.66972518e-01,  3.01892199e-02, -2.49630526e-01, -9.71173868e-02,
          4.30593073e-01,  4.5241

In [32]:
grouped_comments = {}
for comment in comments:
    index = comment['index']
    if index not in grouped_comments:
        grouped_comments[index] = []
    grouped_comments[index].append(comment)

AttributeError: 'list' object has no attribute 'get'

In [27]:
import torch
from transformers import BertTokenizer, BertModel
import numpy as np

model_name = './bert-base-chinese/'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name)


grouped_keywords = {}
for keyword in comments:
    index = keyword['index']
    if index not in grouped_keywords:
        grouped_keywords[index] = []
    grouped_keywords[index].append(keyword)

# 定义注意力权重计算函数，这里使用均匀权重
def calculate_attention_weights(group):
    num_keywords = len(group)
    return np.ones(num_keywords) / num_keywords

# 存储最终结果的列表
final_features = []

# 遍历分组后的数据
for index, group in grouped_keywords.items():
    # 对每个 'index' 组内的评论进行处理
    all_input_ids = []
    all_attention_weights = []

    for keyword in group:
        inputs = tokenizer(keyword['comments'], return_tensors='pt', padding=True, truncation=True, max_length=50)
        outputs = model(**inputs)
        last_hidden_states = outputs.last_hidden_state
        feature = last_hidden_states.mean(dim=1)
        all_input_ids.append(feature.flatten().detach().numpy())

    # 计算注意力权重
    attention_weights = calculate_attention_weights(group)

    # 使用注意力权重对特征进行融合
    merged_feature = np.average(all_input_ids, axis=0, weights=attention_weights)

    # 存储最终结果
    final_features.append({'index': index, 'merged_feature': merged_feature})

# 打印最终结果
for final_feature in final_features:
    print(final_feature)


TypeError: list indices must be integers or slices, not str

In [13]:
import torch
from transformers import BertTokenizer, BertModel

model_name = './bert-base-chinese/'
tokenizer = BertTokenizer.from_pretrained(model_name)

inputs = tokenizer(keywords, return_tensors='pt', padding=True, truncation=True)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


ValueError: too many values to unpack (expected 2)

In [26]:
model = BertModel.from_pretrained(model_name)

with torch.no_grad():
    outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state
features = last_hidden_states.mean(dim=1)  

print(features)


tensor([[ 0.1991, -0.0138, -0.1109,  ...,  0.2633,  0.0440, -0.0900],
        [ 0.1991, -0.0138, -0.1109,  ...,  0.2633,  0.0440, -0.0900],
        [ 0.1991, -0.0138, -0.1109,  ...,  0.2633,  0.0440, -0.0900],
        ...,
        [-0.2289,  0.5408, -0.4242,  ..., -0.0441, -0.1671, -0.2258],
        [-0.2289,  0.5408, -0.4242,  ..., -0.0441, -0.1671, -0.2258],
        [-0.2289,  0.5408, -0.4242,  ..., -0.0441, -0.1671, -0.2258]])


In [7]:
features.shape

NameError: name 'features' is not defined

In [1]:
features_path = './fea/text_f.pt'

In [2]:
torch.save(features, features_path)

NameError: name 'torch' is not defined